services:
  mongodb:
    image: mongo:6.0
    container_name: dwh_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: dwh_finance

  mongo-express:
    image: mongo-express
    container_name: dwh_mongo_ui
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb

  spark-master:
    build:
      context: .
      dockerfile: spark.Dockerfile
    image: dwh-finance/spark:3.5.8
    container_name: dwh_spark_master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - ../src:/opt/dwh/src:ro
    ports:
      - "8080:8080"
      - "7077:7077"

  spark-worker:
    build:
      context: .
      dockerfile: spark.Dockerfile
    image: dwh-finance/spark:3.5.8
    container_name: dwh_spark_worker
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
      --cores 1 --memory 1G
    environment:
      - SPARK_NO_DAEMONIZE=true
    depends_on:
      - spark-master

volumes:
  mongodb_data:
